edition = "2021"
format_macro_bodies = true
format_strings = true
imports_granularity = "Crate"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
imports_layout = "Vertical"
